framework:
    asset_mapper:
        paths:
            - assets/
            - public/uploads/models/
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
